// Generated by CoffeeScript 1.6.3
(function() {
  var defineConfig, document, extend, gId, window;

  window = this;

  document = window.document;

  /*
  * 获取元素
  * @param  {Object} id 
  * @return {Object}
  */


  gId = function(id) {
    return document.getElementById(id);
  };

  /*
  * 拓展
  * @param  {Object} define 默认配置项
  * @param  {Object} source    
  * @return {Object}
  */


  extend = function(define, source) {
    var k;
    for (k in source) {
      define[k] = source[k];
    }
    return define;
  };

  /*
  * 默认参数
  * @type {Object}
  */


  defineConfig = {
    obj: gId('demo'),
    step: 25,
    delay: 1000,
    speed: 30
  };

  /*
  * 主函数
  * @param  {Object} options 参数
  * @主函数
  */


  window.scroll = function(options) {
    var delay, o, p, scrolling, speed, start, step, t;
    options = extend(defineConfig, options);
    t = null;
    step = options.step;
    delay = options.delay;
    speed = options.speed;
    p = 0;
    o = options.obj;
    /*
    	 * 复制一份内容
    */

    o.innerHTML += o.innerHTML;
    o.onmouseover = function() {
      p = 1;
    };
    o.onmouseout = function() {
      p = 0;
    };
    o.scrollTop = 0;
    /*
    	 * 运动函数
    */

    start = function() {
      t = setInterval(scrolling, speed);
      if (!p) {
        o.scrollTop += 1;
      }
    };
    /*
    	 * 执行函数
    	 * @return {[type]} [description]
    */

    scrolling = function() {
      if (o.scrollTop % step !== 0) {
        o.scrollTop += 1;
        if (o.scrollTop >= o.scrollHeight / 2) {
          o.scrollTop = 0;
        }
      } else {
        clearInterval(t);
        setTimeout(start, delay);
      }
    };
    setTimeout(start, delay);
  };

}).call(this);
